# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-04 15:39
from __future__ import unicode_literals

from django.db import migrations

def add_superuser(apps, schema_editor):
    # Normally one uses `apps.get_model()` in a migration, but we
    # need a regular import here to have access to `set_password()`.
    from django.contrib.auth.models import User
    superuser = User(username='admin', email='admin@example.com', is_staff=True, is_superuser=True)
    superuser.set_password('1234')
    superuser.save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_superuser)
    ]
